export const LEGAL_METROLOGY_RULES = [
  {
    id: 'LM-01',
    key: 'manufacturerIdentity',
    title: 'Manufacturer / packer / importer name',
    legalBasis: 'Rule 6(1)(a), Rule 10',
    pattern: /(manufactur(?:er|ed|ing)?|manufactured\s+by|packed\s+by|packer|importer|निर्माता|निर्मित|पैक(?:र|िंग)?|आयातक)/i,
    weight: 8,
  },
  {
    id: 'LM-02',
    key: 'completeAddress',
    title: 'Complete manufacturer / packer / importer address',
    legalBasis: 'Rule 10(1)',
    pattern: /((address|addr\.?|पता)\s*[:\-]?|\b\d{6}\b|pin\s*(code)?|pincode|\b(?:uttarakhand|delhi|mumbai|india|ind|up|uttar\s*pradesh)\b)/i,
    weight: 7,
  },
  {
    id: 'LM-03',
    key: 'actualBusinessName',
    title: 'Actual corporate / business name identifiable',
    legalBasis: 'Rule 10(2)',
    pattern: /(manufactured\s+by|packed\s+by|marketed\s+by|imported\s+by|निर्माता|पैक|आयातक|manufactur|packer|importer)/i,
    weight: 4,
  },
  {
    id: 'LM-04',
    key: 'origin',
    title: 'Country of origin (where applicable)',
    legalBasis: 'Rule 6 / imported packages',
    pattern: /(country\s+of\s+origin|made\s+in|product\s+of|origin\s*[:\-]|country\s*[:\-]|निर्मित\s*स्थान|उत्पत्ति|देश\s*का\s*मूल)/i,
    weight: 5,
  },
  {
    id: 'LM-05',
    key: 'commodity',
    title: 'Common / generic name of commodity',
    legalBasis: 'Rule 6(1)(b)',
    pattern: /(product|commodity|contents|material|powder|spices?|rice|flour|soap|detergent|shampoo|oil|sugar|salt|tea|coffee|biscuits?|उत्पाद|सामग्री|वस्तु|मसाला|चावल|आटा|साबुन|तेल|चीनी|नमक)/i,
    weight: 8,
  },
  {
    id: 'LM-06',
    key: 'multiProductDetails',
    title: 'Name + number/quantity of each product where package has multiple products',
    legalBasis: 'Rule 6(1)(b)',
    pattern: /(combo|pack\s+of|set\s+of|pieces?|pcs|units?|pair|each|x\s*\d+|\b\d+\s*(?:pcs|pieces|units?|items?)\b|कॉम्बो|पीस|नग)/i,
    weight: 4,
    conditional: true,
  },
  {
    id: 'LM-07',
    key: 'quantity',
    title: 'Net quantity in standard unit / number',
    legalBasis: 'Rule 6(1)(c), Rules 11–13',
    pattern: /(net\s*(qty|quantity|weight|wt|vol)|net\s*wt\.?|शुद्ध\s*(मात्रा|वजन)|\b\d+(?:\.\d+)?\s?(?:kg|g|mg|l|ml|m|cm|mm|sq\.?\s?m|cm2|m2|pcs|pieces|units?|unit|n|u)\b)/i,
    weight: 10,
  },
  {
    id: 'LM-08',
    key: 'manufactureDate',
    title: 'Month and year of manufacture / packing / applicable date declaration',
    legalBasis: 'Rule 6(1)(d) and amendments',
    pattern: /(mfg|mfd|manufactur(?:ed|e)?|packed|pkd|date\s*(of)?\s*(mfg|manufacture|packing)|\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)['’\s\/-]*\d{2,4}\b|\b(?:0?[1-9]|1[0-2])['’\s\/-]*\d{4}\b|निर्माण|पैकिंग|निर्मित|तिथि)/i,
    weight: 8,
  },
  {
    id: 'LM-09',
    key: 'bestBefore',
    title: 'Best before / use by date where commodity may become unfit for human consumption',
    legalBasis: 'Rule 6(1)(da) / applicable commodity',
    pattern: /(best\s*before|use\s*by|expiry|exp\.?\s*date|use\s*before|उपयोग\s*करें|समाप्ति|बेस्ट\s*बिफोर)/i,
    weight: 5,
    conditional: true,
  },
  {
    id: 'LM-10',
    key: 'mrp',
    title: 'Maximum Retail Price (MRP) / retail sale price',
    legalBasis: 'Rule 6(1)(e)',
    pattern: /(m\.?r\.?p|maximum\s*(retail|retail\s+sale)\s*price|retail\s*sale\s*price|अधिकतम\s*खुदरा\s*मूल्य|खुदरा\s*मूल्य)/i,
    weight: 10,
  },
  {
    id: 'LM-11',
    key: 'mrpInclusiveTaxes',
    title: 'MRP stated inclusive of all taxes',
    legalBasis: 'Rule 2(m), Rule 6(1)(e)',
    pattern: /(m\.?r\.?p|maximum\s*retail\s*price)[^\n]{0,80}(incl\.?|inclusive)\s*(of\s*)?(all\s*)?tax(?:es)?|incl\.?\s*of\s*all\s*tax(?:es)?|सभी\s*कर|करों\s*सहित/i,
    weight: 6,
  },
  {
    id: 'LM-12',
    key: 'unitSalePrice',
    title: 'Unit sale price in prescribed unit where applicable',
    legalBasis: 'Rule 6(11), amendments effective from 2022/2024',
    pattern: /(unit\s*sale\s*price|unit\s*price|per\s*(g|gram|kg|kilogram|ml|millilitre|litre|l|cm|centimetre|m|metre|number|unit)|प्रति\s*(ग्राम|किलोग्राम|मिलीलीटर|लीटर|इकाई|नग|संख्या))/i,
    weight: 7,
    conditional: true,
  },
  {
    id: 'LM-13',
    key: 'consumerCare',
    title: 'Consumer care contact: name/address/phone/email',
    legalBasis: 'Rule 6(2)',
    pattern: /(consumer\s+care|customer\s+care|consumer\s+complaint|helpline|toll[- ]?free|contact\s+us|e[- ]?mail|email|phone|mobile|care@|उपभोक्ता\s*देखभाल|हेल्पलाइन|संपर्क|ईमेल|मोबाइल|फोन)/i,
    weight: 8,
  },
  {
    id: 'LM-14',
    key: 'dimensions',
    title: 'Dimensions where dimensions are relevant',
    legalBasis: 'Rule 6(1)(f), Rules 14–17',
    pattern: /(dimension|dimensions|size\s*[:x×]|length|width|height|depth|diameter|लंबाई|चौड़ाई|ऊंचाई|गहराई|आकार|आयाम|\b\d+(?:\.\d+)?\s*[x×]\s*\d+)/i,
    weight: 4,
    conditional: true,
  },
  {
    id: 'LM-15',
    key: 'quantityUnits',
    title: 'Quantity uses an appropriate standard unit / number',
    legalBasis: 'Rules 12–13',
    pattern: /\b\d+(?:\.\d+)?\s?(?:g|kg|mg|ml|l|m|cm|mm|m2|cm2|sq\.?\s?m|litre|liter|gram|kilogram|metre|meter|centimetre|centimeter|N|U|pcs|pieces|units?)\b/i,
    weight: 5,
  },
  {
    id: 'LM-16',
    key: 'quantityMisleadingWords',
    title: 'No misleading quantity wording detected',
    legalBasis: 'Rule 12(6)',
    pattern: /\b(?:minimum|not\s+less\s+than|average|about|approximately|approx\.?|कम\s*से\s*कम|लगभग|औसत|न्यूनतम)\b/i,
    weight: 5,
    negative: true,
  },
  {
    id: 'LM-17',
    key: 'language',
    title: 'Mandatory declarations in Hindi (Devanagari) or English',
    legalBasis: 'Rule 9(4)',
    pattern: /[A-Za-z]{2,}|[\u0900-\u097F]{2,}/,
    weight: 3,
  },
  {
    id: 'LM-18',
    key: 'visualManner',
    title: 'Legible, prominent and prescribed presentation',
    legalBasis: 'Rules 7–9',
    visualOnly: true,
  },
  {
    id: 'LM-19',
    key: 'principalDisplayPanel',
    title: 'Required declarations appear on principal display panel',
    legalBasis: 'Rule 8',
    visualOnly: true,
  },
  {
    id: 'LM-20',
    key: 'contrast',
    title: 'MRP and net quantity numerals contrast with background',
    legalBasis: 'Rule 9(1)(b)',
    visualOnly: true,
  },
  {
    id: 'LM-21',
    key: 'quantitySpacing',
    title: 'Required clear space around quantity declaration',
    legalBasis: 'Rule 8(1)',
    visualOnly: true,
  },
  {
    id: 'LM-22',
    key: 'outerWrapper',
    title: 'Outer wrapper/container carries required declarations where applicable',
    legalBasis: 'Rule 9(3)',
    visualOnly: true,
  },
];
